var JumpSFX= new Audio('../RoboGranny-master/sounds/Jump.wav');
var PowerupSFX = new Audio('../RoboGranny-master/sounds/Powerup.wav');
var PowerupSFX1= new Audio('../RoboGranny-master/sounds/Powerup1.wav');
var ShieldSFX= new Audio('../RoboGranny-master/sounds/Shield.wav');
var ShootSFX= new Audio('../RoboGranny-master/sounds/Shoot.wav');
var LaserSFX= new Audio('../RoboGranny-master/sounds/Laser_Shoot.wav');          //More SFX will be added here//
var DeathSFX= new Audio('../RoboGranny-master/sounds/Death.wav');
var HurtSFX= new Audio('../RoboGranny-master/sounds/Hit_Hurt.wav');
var DashSFX= new Audio('../RoboGranny-master/sounds/Dash.wav');
var CoinSFX= new Audio('../RoboGranny-master/sounds/Coin.wav');
var ExplosionSFX= new Audio('../RoboGranny-master/sounds/Explosion.wav');
var PortalSFX= new Audio('../RoboGranny-master/sounds/Portal.wav');
